# This is a basic workflow that is manually triggered

name: dockerfile
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: create dockerfile
      run: docker build . -t worktogether-app:latest
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
        with:
          username: ${{ secrets.shaony00 }}
          password: ${{ secrets.Zq2xUifpn&Jb!7&U&9Z@ }}
      
    - name: Push Docker image to Docker Hub
      run: docker push worktogether-app:latest
