version: '3.8'
services:
  app:
    image: shaony00/worktogether
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - DATABASE_URL=sqlsrv://sa:sql2022_@db/PPE

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=sql2022_
    ports:
      - "1434:1433"
    volumes:
      - db-data:/var/opt/mssql

volumes:
  db-data: