name: Docker

on:
  push:
    branches:
      "master"

jobs:
#  cypress-tests:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v2
#
#      - name: Install dependencies
#        run: npm install
#
#      - name: Run Cypress tests
#        run: npm run cypress:run
#
#      - name: Check Cypress test status
#        run: |
#          if grep -q "All specs passed!" cypress/output.txt;
#          else
#            exit 1
#          fi
#
#  push-if-tests-passed:
#    needs: cypress-tests
#    runs-on: ubuntu-latest
#    if: ${{ needs.cypress-tests.result == 'success' }}
#
    steps:
      - name: Push to master branch
        uses: ad-m/github-push-action@master

  build:
    needs: push-if-tests-passed
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/worktogether:${{ GITHUB.SHA }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.IPDEVOPS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEYSSHDEVOPS }}
          script: |
            sed -i "s|\(worktogether:\).*|\1${{github.sha}}|" docker-compose.yml
            docker compose up -d
